### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by haleyngonadi** [naomiaro/video-waveform-subtitle-editor#1]
Hey, I'm wondering if you ever got this working? I'm trying to accomplish something similar but i"m not sure how best to make the waveform for the YouTube video... I hope you can maybe help me :)

How should this be run?

**Comment by ambiflextrous** [comment]
Trying to do the same thing, did ever get around it?

**Comment by naomiaro** [comment]
This was running with a modified version of [Waveform Playlist](https://github.com/naomiaro/waveform-playlist) at some point 

There were some issues with drift from the video if there was some network lag at the current state of this project. It would need more work to sync those up, was looking to try using something like the [Timing Object](http://webtiming.github.io/timingobject/) in a future version.

Currently I'm working on porting Waveform Playlist to React, then I might look more into this editor again.
